version: '3'

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app                                      # The project folder
      - elixir-deps:/app/deps                       # Elixir dependencies
      - elixir-build:/app/_build                    # Elixir build files
      - tmp:/tmp                                    # Torrent downloads location
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
volumes:
  elixir-deps:
  elixir-build:
  node-modules:
  tmp:
